### ISSUE TITLE
`stimmung-themes--toggle-prompt` gets its result backwards

### ISSUE THREAD

**Issue by slotThe** [motform/stimmung-themes#11]
[This here](https://github.com/motform/stimmung-themes/blob/92a89be/stimmung-themes.el#L84-L85) should probably be 

``` emacs-lisp
(pcase theme
	  ('stimmung-themes-light (stimmung-themes-load-light))
	  ('stimmung-themes-dark  (stimmung-themes-load-dark)))
```

instead, since whenever this is called we are definitely not using any of the `stimmung-themes` and so we should listen to the user in this case :)

**Comment by motform** [comment]
It really should! Thank you for catching that, I must have just copy-pasted from the non-prompt case. Fixed it, thanks!
