### ISSUE TITLE
Doom Emacs: "Invalid face box"

### ISSUE THREAD

**Issue by Jeiwan** [motform/stimmung-themes#12]
I'm getting this error when trying to use this theme in Doom Emacs:
> Invalid face box: :line-width, (1 . -1), :color, "gray60"

It works after I comment these lines out:
https://github.com/motform/stimmung-themes/blob/master/stimmung-themes-light-theme.el#L375-L376
https://github.com/motform/stimmung-themes/blob/master/stimmung-themes-light-theme.el#L401
https://github.com/motform/stimmung-themes/blob/master/stimmung-themes-dark-theme.el#L377-L378
https://github.com/motform/stimmung-themes/blob/master/stimmung-themes-dark-theme.el#L403

**Comment by motform** [comment]
Hi @Jeiwan,

Nice catch! I can't remember where I got `(1 . -1)` from, but it does not seem to do anything different from just `1`. I pushed and update that removes those instances and swaps all `:line-width -1` to `:line-width 1`.

Does that fix it?

**Comment by Jeiwan** [comment]
Yes, it works now 👍
