### ISSUE TITLE
Create a function to toggle between light and dark

### ISSUE THREAD

**Issue by dpassen** [motform/stimmung-themes#3]
Inspired by [modus-themes](https://github.com/protesilaos/modus-themes/blob/03f7046dff86c5342af778ad3f9850af7e950aed/modus-themes.el#L4298), would it be possible to have a function to toggle between light and dark variants?

**Comment by motform** [comment]
Great idea @dpassen! I whipped up a simple implementation of this based on modus. Give it a try! I'll investigate the extra work that modus does and maybe implement that to make the function more robust later.

**Comment by dpassen** [comment]
Works for me

**Comment by motform** [comment]
Great! It seems like the extra work modus is doing is ensuring that the theme is properly loaded and that the one getting un-toggled gets flushed out, which probably adds some robustness. I'll look over that some day, but in the meanwhile, this works under assumptions that the user knows what they are doing.
