### ISSUE TITLE
Dark theme references unavailable light theme variable

### ISSUE THREAD

**Issue by Walheimat** [motform/stimmung-themes#8]
I noticed that I can only load the dark theme after also requiring the light theme since several color definitions for the dark theme reference `stimmung-themes-light-highlight-color`. Since I assume that this is on purpose, maybe these colors could be required from a common package?

**Comment by motform** [comment]
Hi @Walheimat,

That's a good catch! The dark theme using the light highlight is simply a copy-paste mistake, which is now corrected. I also implemented your suggestion of refactoring all variables into the common file, that makes a lot of sense. See [b4c97df](https://github.com/motform/stimmung-themes/commit/b4c97df76f3cb56dec92678b449e2a1ca3f40289). In the future (this afternoon) I'll also add an `init` function for both of the themes ala `modus`.

Does that fix the issue?

**Comment by Walheimat** [comment]
I think if you added a

```elisp
(require 'stimmung-themes)
```

into the dark/light packages it would work now. But maybe your init functions will take care of this as well.

**Comment by motform** [comment]
I think that sound like a great idea regardless of the validity of my fix, so I added that as well. Thanks!

**Comment by Walheimat** [comment]
Thanks. Works nicely for me now, can close from my side.
