### ISSUE TITLE
Can't see company selection in dark theme.

### ISSUE THREAD

**Issue by lakkiy** [motform/stimmung-themes#9]
Here is how it looks in dark/light theme.
Basically I can't see it in dark theme.

<img width="183" alt="Screen Shot 2022-03-28 at 15 07 14" src="https://user-images.githubusercontent.com/24653356/160344418-9872ab20-f161-45af-ad00-5c66c57e9e7c.png">

<img width="205" alt="Screen Shot 2022-03-28 at 15 07 53" src="https://user-images.githubusercontent.com/24653356/160344480-8ea96a61-2ebc-49b7-a63d-512e1e2119f0.png">

**Comment by motform** [comment]
Hi @404cn,

That's a good catch, I'll install company and give it a look-over later today. Those are some of the oldest faces and I think they could use a general touch up.

**Comment by motform** [comment]
I pushed an update that overhauls the faces used by `company` to be more in line with the rest of the theme. Could you try them out and see if they do what you expect? I don't use company, so I hade to make some assumptions in places.

**Comment by lakkiy** [comment]
> I pushed an update that overhauls the faces used by `company` to be more in line with the rest of the theme. Could you try them out and see if they do what you expect? I don't use company, so I hade to make some assumptions in places.

Yes it works
